# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E5_ComprasDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1271, 381)
        Dialog.setStyleSheet("background-color: rgb(255, 211, 212);")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 181, 91))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/Logos/LogoUAT.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(1090, 0, 181, 91))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/Logos/LogoFIT.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(1090, 290, 181, 91))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/Logos/RhineLab.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.txtCompra8 = QtWidgets.QLineEdit(Dialog)
        self.txtCompra8.setEnabled(False)
        self.txtCompra8.setGeometry(QtCore.QRect(880, 130, 113, 41))
        self.txtCompra8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtCompra8.setObjectName("txtCompra8")
        self.txtCompra2 = QtWidgets.QLineEdit(Dialog)
        self.txtCompra2.setEnabled(False)
        self.txtCompra2.setGeometry(QtCore.QRect(160, 130, 113, 41))
        self.txtCompra2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtCompra2.setObjectName("txtCompra2")
        self.txtCompra6 = QtWidgets.QLineEdit(Dialog)
        self.txtCompra6.setEnabled(False)
        self.txtCompra6.setGeometry(QtCore.QRect(640, 130, 113, 41))
        self.txtCompra6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtCompra6.setObjectName("txtCompra6")
        self.txtCompra3 = QtWidgets.QLineEdit(Dialog)
        self.txtCompra3.setEnabled(False)
        self.txtCompra3.setGeometry(QtCore.QRect(280, 130, 113, 41))
        self.txtCompra3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtCompra3.setObjectName("txtCompra3")
        self.txtCompra1 = QtWidgets.QLineEdit(Dialog)
        self.txtCompra1.setEnabled(False)
        self.txtCompra1.setGeometry(QtCore.QRect(40, 130, 113, 41))
        self.txtCompra1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtCompra1.setObjectName("txtCompra1")
        self.txtCompra4 = QtWidgets.QLineEdit(Dialog)
        self.txtCompra4.setEnabled(False)
        self.txtCompra4.setGeometry(QtCore.QRect(400, 130, 113, 41))
        self.txtCompra4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtCompra4.setObjectName("txtCompra4")
        self.txtCompra9 = QtWidgets.QLineEdit(Dialog)
        self.txtCompra9.setEnabled(False)
        self.txtCompra9.setGeometry(QtCore.QRect(1000, 130, 113, 41))
        self.txtCompra9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtCompra9.setObjectName("txtCompra9")
        self.txtCompra5 = QtWidgets.QLineEdit(Dialog)
        self.txtCompra5.setEnabled(False)
        self.txtCompra5.setGeometry(QtCore.QRect(520, 130, 113, 41))
        self.txtCompra5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtCompra5.setObjectName("txtCompra5")
        self.txtCompra7 = QtWidgets.QLineEdit(Dialog)
        self.txtCompra7.setEnabled(False)
        self.txtCompra7.setGeometry(QtCore.QRect(760, 130, 113, 41))
        self.txtCompra7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtCompra7.setObjectName("txtCompra7")
        self.txtCompra10 = QtWidgets.QLineEdit(Dialog)
        self.txtCompra10.setEnabled(False)
        self.txtCompra10.setGeometry(QtCore.QRect(1120, 130, 113, 41))
        self.txtCompra10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtCompra10.setObjectName("txtCompra10")
        self.btnCompras_2 = QtWidgets.QPushButton(Dialog)
        self.btnCompras_2.setGeometry(QtCore.QRect(450, 210, 371, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnCompras_2.setFont(font)
        self.btnCompras_2.setStyleSheet("background-color: rgb(255, 224, 235);")
        self.btnCompras_2.setObjectName("btnCompras_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnCompras_2.setText(_translate("Dialog", "Aceptar"))
import resources_rc
