# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E8_UvasDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("background-color: rgb(255, 55, 235);")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.txtPrecioKilo = QtWidgets.QLineEdit(Dialog)
        self.txtPrecioKilo.setGeometry(QtCore.QRect(80, 80, 241, 51))
        self.txtPrecioKilo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtPrecioKilo.setObjectName("txtPrecioKilo")
        self.txtOK = QtWidgets.QPushButton(Dialog)
        self.txtOK.setGeometry(QtCore.QRect(20, 180, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtOK.setFont(font)
        self.txtOK.setStyleSheet("background-color: rgb(255, 224, 235);")
        self.txtOK.setObjectName("txtOK")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "Deberias vender el kilo a:"))
        self.txtOK.setText(_translate("Dialog", "OK"))
