# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E8_UvasMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(999, 517)
        MainWindow.setStyleSheet("background-color: rgb(122, 0, 116);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 181, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Logos/LogoUAT.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(810, 0, 181, 91))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Logos/LogoFIT.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(810, 370, 181, 91))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/Logos/RhineLab.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 130, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.btnCompras = QtWidgets.QPushButton(self.centralwidget)
        self.btnCompras.setGeometry(QtCore.QRect(520, 130, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnCompras.setFont(font)
        self.btnCompras.setStyleSheet("background-color: rgb(255, 224, 235);")
        self.btnCompras.setObjectName("btnCompras")
        self.txtPrecio = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPrecio.setGeometry(QtCore.QRect(230, 130, 241, 51))
        self.txtPrecio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtPrecio.setObjectName("txtPrecio")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 220, 181, 201))
        self.groupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox.setObjectName("groupBox")
        self.rtbnTipoA = QtWidgets.QRadioButton(self.groupBox)
        self.rtbnTipoA.setGeometry(QtCore.QRect(20, 40, 95, 20))
        self.rtbnTipoA.setChecked(True)
        self.rtbnTipoA.setObjectName("rtbnTipoA")
        self.rbtnTipoB = QtWidgets.QRadioButton(self.groupBox)
        self.rbtnTipoB.setGeometry(QtCore.QRect(20, 90, 95, 20))
        self.rbtnTipoB.setObjectName("rbtnTipoB")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(290, 220, 181, 201))
        self.groupBox_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.rbtnTamano1 = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbtnTamano1.setGeometry(QtCore.QRect(20, 40, 95, 20))
        self.rbtnTamano1.setChecked(True)
        self.rbtnTamano1.setObjectName("rbtnTamano1")
        self.rbtnTamano2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbtnTamano2.setGeometry(QtCore.QRect(20, 90, 95, 20))
        self.rbtnTamano2.setObjectName("rbtnTamano2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 999, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Precio Base"))
        self.btnCompras.setText(_translate("MainWindow", "CALCULA PRECIO"))
        self.groupBox.setTitle(_translate("MainWindow", "TIPO"))
        self.rtbnTipoA.setText(_translate("MainWindow", "A"))
        self.rbtnTipoB.setText(_translate("MainWindow", "B"))
        self.groupBox_2.setTitle(_translate("MainWindow", "TAMAÑO"))
        self.rbtnTamano1.setText(_translate("MainWindow", "1"))
        self.rbtnTamano2.setText(_translate("MainWindow", "2"))
import resources_rc
