# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P1_Ejemplo.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1253, 829)
        MainWindow.setStyleSheet("background-color: rgb(255, 224, 235);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnSaludar = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaludar.setGeometry(QtCore.QRect(510, 250, 211, 71))
        self.btnSaludar.setStyleSheet("background-color: rgb(170, 0, 127);\n"
                                      "color: rgb(255, 255, 255);")
        self.btnSaludar.setObjectName("btnSaludar")
        self.txtValor = QtWidgets.QLineEdit(self.centralwidget)
        self.txtValor.setGeometry(QtCore.QRect(510, 190, 211, 41))
        self.txtValor.setStyleSheet("background-color: rgb(170, 0, 127);\n"
                                    "color: rgb(255, 255, 255);")
        self.txtValor.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValor.setObjectName("txtValor")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1030, 20, 201, 121))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Logos/LogoFIT.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 201, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Logos/LogoUAT.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1030, 640, 201, 121))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/Logos/RhineLab.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1253, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSaludar.setText(_translate("MainWindow", "Saludo"))
        self.txtValor.setText(_translate("MainWindow", "H"))


import resources_rc
