# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P3_ComunicacionVentanas.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1258, 818)
        MainWindow.setStyleSheet("background-color: rgb(255, 224, 235);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnSumar = QtWidgets.QPushButton(self.centralwidget)
        self.btnSumar.setGeometry(QtCore.QRect(140, 240, 211, 71))
        self.btnSumar.setStyleSheet("background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.btnSumar.setObjectName("btnSumar")
        self.txtValorA = QtWidgets.QLineEdit(self.centralwidget)
        self.txtValorA.setGeometry(QtCore.QRect(30, 190, 211, 41))
        self.txtValorA.setStyleSheet("background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.txtValorA.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValorA.setObjectName("txtValorA")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1030, 20, 201, 121))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Logos/LogoFIT.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 201, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Logos/LogoUAT.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1030, 640, 201, 121))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/Logos/RhineLab.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.txtValorB = QtWidgets.QLineEdit(self.centralwidget)
        self.txtValorB.setGeometry(QtCore.QRect(250, 190, 211, 41))
        self.txtValorB.setStyleSheet("background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.txtValorB.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValorB.setObjectName("txtValorB")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1258, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSumar.setText(_translate("MainWindow", "Sumar"))
        self.txtValorA.setText(_translate("MainWindow", "H"))
        self.txtValorB.setText(_translate("MainWindow", "H"))
import resources_rc
